### PR TITLE
Update to work with newer errors

### PR DESCRIPTION
**Pull request by Manishearth**
This works around the error from https://github.com/rust-lang/rust/issues/120363, fixing https://github.com/yaahc/displaydoc/issues/46

### CODE REVIEW

**Comment by Manishearth** [comment]
Would also love to get a release with this fix.

**Comment by Manishearth** [comment]
Nightly CI fails for preexisting reasons.

**Comment by Urgau** [comment]
There is already https://github.com/yaahc/displaydoc/pull/47 to address the issue.

**Comment by Manishearth** [comment]
This got fixed, in a simpler/cleaner way.

**Pull request closed without merging**
